services:
  postgres:
    image: postgres:18
    container_name: app_ke_toan_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_ke_toan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_ke_toan"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
