export const activeAccountingAccounts = [
  { code: "1111", name: "Tien Viet Nam tai quy", type: "asset", active: true },
  { code: "1121", name: "Tien Viet Nam gui ngan hang", type: "asset", active: true },
  { code: "131", name: "Phai thu cua khach hang", type: "asset", active: true },
  { code: "1331", name: "Thue GTGT duoc khau tru cua hang hoa, dich vu", type: "asset", active: true },
  { code: "152", name: "Nguyen lieu, vat lieu", type: "asset", active: true },
  { code: "153", name: "Cong cu, dung cu", type: "asset", active: true },
  { code: "156", name: "Hang hoa", type: "asset", active: true },
  { code: "2111", name: "Tai san co dinh huu hinh", type: "asset", active: true },
  { code: "2141", name: "Hao mon tai san co dinh huu hinh", type: "contra_asset", active: true },
  { code: "242", name: "Chi phi tra truoc", type: "asset", active: true },
  { code: "331", name: "Phai tra cho nguoi ban", type: "liability", active: true },
  { code: "3331", name: "Thue GTGT phai nop", type: "liability", active: true },
  { code: "334", name: "Phai tra nguoi lao dong", type: "liability", active: true },
  { code: "3388", name: "Phai tra, phai nop khac", type: "liability", active: true },
  { code: "4111", name: "Von gop cua chu so huu", type: "equity", active: true },
  { code: "5111", name: "Doanh thu ban hang hoa", type: "revenue", active: true },
  { code: "515", name: "Doanh thu hoat dong tai chinh", type: "revenue", active: true },
  { code: "632", name: "Gia von hang ban", type: "expense", active: true },
  { code: "635", name: "Chi phi tai chinh", type: "expense", active: true },
  { code: "641", name: "Chi phi ban hang", type: "expense", active: true },
  { code: "642", name: "Chi phi quan ly doanh nghiep", type: "expense", active: true },
  { code: "711", name: "Thu nhap khac", type: "income", active: true },
  { code: "811", name: "Chi phi khac", type: "expense", active: true },
  { code: "911", name: "Xac dinh ket qua kinh doanh", type: "closing", active: true },
] as const;
