"use client";

import {
  ArrowRight,
  Bot,
  Calculator,
  Database,
  BookOpen,
  ArrowLeft,
  ArrowLeftRight,
  BadgeDollarSign,
  ChevronDown,
  CircleDollarSign,
  FileText,
  LayoutGrid,
  List,
  Landmark,
  LockKeyhole,
  LogOut,
  Minus,
  ReceiptText,
  Save,
  Search,
  ShieldCheck,
  ShoppingCart,
  PieChart,
  Printer,
  RefreshCw,
  Send,
  TrendingUp,
  Upload,
  User,
  ChevronUp,
  WalletCards,
  Warehouse,
} from "lucide-react";

const icons = {
  ArrowRight,
  ArrowLeft,
  BookOpen,
  Bot,
  ArrowLeftRight,
  BadgeDollarSign,
  Calculator,
  Database,
  ChevronDown,
  CircleDollarSign,
  FileText,
  LayoutGrid,
  List,
  Landmark,
  LockKeyhole,
  LogOut,
  Minus,
  PieChart,
  Printer,
  RefreshCw,
  Send,
  ReceiptText,
  Save,
  Search,
  ShieldCheck,
  ShoppingCart,
  TrendingUp,
  Upload,
  User,
  ChevronUp,
  WalletCards,
  Warehouse,
};

export type IconName = keyof typeof icons;

export function AppIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = icons[name as IconName] ?? LayoutGrid;
  return <Icon aria-hidden="true" size={size} strokeWidth={2.1} />;
}
